.TH "jeo-drivers" "1" "12 March 2015" "version 0.5"
.SH NAME
jeo drivers
.SH DESCRIPTION
The drivers command displays information about all available drivers.
.PP
jeo drivers
.PP
The command takes a single argument, the name of a driver, and displays more detailed information about that specific driver, such as the connection parameters for the driver, and any aliases for it.
.PP
jeo drivers postgis
.SH USAGE
jeo drivers <driver>
.SH OPTIONS
-h --help: Provides help for this command.  The default is false
.PP
-x --debug: Runs the command in debug mode.  The default is false
.PP
